name: Weekly ping the FDP Index

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 2"
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependency
        uses: py-actions/py-dependency-install@v4
        with:
          path: "script/requirements.txt"

      - name: Ping FDP test index
        id: ping-test-index
        working-directory: ./script
        env:
          FDP_INDEX_URL: "http://178.63.49.197:8070"
          FDP_URL: "https://fdp.wikipathways.org/"
        run: 'python ping.py'

      - name: Ping FDP index
        id: ping-index
        working-directory: ./script
        env:
          FDP_INDEX_URL: "https://index.vp.ejprarediseases.org/"
          FDP_URL: "https://fdp.wikipathways.org/"
        run: 'python ping.py'
