name: Validation

on:
  workflow_dispatch:
  push:
    paths:
      - '**/index.html'
  pull_request:

jobs:
  validate-rdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Safe files as .ttl
        run: |
          cp index.html index.ttl
          cp catalog/index.html catalog/index.ttl
          cp dataset/20230210/index.html dataset/20230210/index.ttl

      - name: Validate FDP
        uses: vemonet/jena-riot-action@v3.14
        with:
          input: index.ttl

      - name: Validate Catalog
        uses: vemonet/jena-riot-action@v3.14
        with:
          input: catalog/index.ttl

      - name: Validate Datasets
        uses: vemonet/jena-riot-action@v3.14
        with:
          input: dataset/20230210/index.ttl

  ping:
    runs-on: ubuntu-latest
    needs: validate-rdf
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependency
        uses: py-actions/py-dependency-install@v4
        with:
          path: "script/requirements.txt"

      - name: Ping FDP index
        id: ping-index
        working-directory: ./script
        env:
          FDP_INDEX_URL: "http://178.63.49.197:8070"
          FDP_URL: "https://fdp.wikipathways.org/"
        run: 'python ping.py'
