name: Validation

on:
  push:
  pull_request:

jobs:
  validate-rdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Validate FDP
      - uses: vemonet/jena-riot-action@v3.14
        with:
          input: index.html

      - name: Validate Catalog
      - uses: vemonet/jena-riot-action@v3.14
        with:
          input: catalog/index.html

      - name: Validate Datasets
      - uses: vemonet/jena-riot-action@v3.14
        with:
          input: datasets/20230210/index.html
