name: Validation

on:
  push:
  pull_request:

jobs:
  validate-rdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Safe files as .ttl
        run: |
          cp index.html index.ttl
          cp catalog/index.html catalog/index.ttl
          cp dataset/20230210/index.html dataset/20230210/index.ttl

      - name: Validate FDP
        uses: vemonet/jena-riot-action@v3.14
        with:
          input: index.ttl

      - name: Validate Catalog
        uses: vemonet/jena-riot-action@v3.14
        with:
          input: catalog/index.ttl

      - name: Validate Datasets
        uses: vemonet/jena-riot-action@v3.14
        with:
          input: datasets/20230210/index.ttl
